eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 1
    instance-info-replication-interval-seconds: 1
    serviceUrl:
      defaultZone: http://root:root@eureka1:8761/eureka/,http://root:root@eureka2:8762/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: http://localhost:8080/git/root/SpringCloudConfig.git
          force-pull: true
          clone-on-start: true
          skipSslValidation: true
          username: root
          password: root
          refresh-rate: 5
          search-paths:
            - '{application}'

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
