cache:
  redisbak:
    enable: false
  caffeine:
    enable: true
spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
