############################################
# DataSource - druid    Mysql???
############################################
# ????????????????????dbType???druid?WallFilter??SQL??
# ??????? com.alibaba.druid.util.JdbcConstants
datasource.druid.mysql.db-type=mysql
datasource.druid.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.druid.mysql.url=jdbc:mysql://127.0.0.1:3308/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
datasource.druid.mysql.username=${MYSQL_BAK_USERNAME:root}
datasource.druid.mysql.password=${MYSQL_BAK_PASSWORD:your_password}
datasource.druid.mysql.type=com.alibaba.druid.pool.DruidDataSource
datasource.druid.mysql.aop-patterns=com.example.demo.service.*
datasource.druid.mysql.filters=stat,wall

# ?????
datasource.druid.mysql.initial-size=5
#????????default=8+
datasource.druid.mysql.max-active=20
# ?????????????????
# ???maxWait?????????????????????
# ??????????useUnfairLock???true??????
datasource.druid.mysql.max-wait=60000
# ????prepared statement????PSCache???????????????
# ???Oracle, ??poolPreparedStatements???true, mysql 5.5????true
datasource.druid.mysql.pool-prepared-statements=true
# ???PSCache???????0????0??poolPreparedStatements???????true?
# ?Druid?????Oracle?PSCache?????????????????????????100???=-1
datasource.druid.mysql.max-open-prepared-statements=100
# ???????????sql?????????????select 'x'?
# ??validationQuery?null,testOnBorrow,testOnBorrow,testOnReturn,testWhileIdle??????????????
datasource.druid.mysql.validation-query=select COUNT(1) from test;
# ??:????????????????????jdbc Statement???void setQueryTimeout(int seconds)??
# mysql?????????????mysql??????
datasource.druid.mysql.validation-query-timeout=1000
# ???????????????????????????????????????
# ??: ???true??validation-query??????
datasource.druid.mysql.test-on-borrow=false
# ?????????????
# ??: ???true??validation-query??????
datasource.druid.mysql.test-on-return=false
# ?????true,??????????????
# ??????????????????timeBetweenEvictionRunsMillis?
# ??validationQuery?????????validation-query???????default=false
datasource.druid.mysql.test-while-idle=true
# ?????minIdle??????????????minEvictableIdleTimeMillis?????keepAlive???default=false
datasource.druid.mysql.keep-alive=true
#??????????????????????????????? default=1??
#??????
# (1)Destroy?????????????????????????minEvictableIdleTimeMillis???????
# (2)testWhileIdle?????????testWhileIdle?????
datasource.druid.mysql.time-between-eviction-runs-millis=60000
#?????????????????????????
datasource.druid.mysql.min-evictable-idle-time-millis=100000
datasource.druid.mysql.max-evictable-idle-time-millis=200000
#????DruidDataSource?????
#datasource.druid.mysql.use-global-data-source-stat=true
datasource.druid.mysql.web-stat-filter.enabled=true
datasource.druid.mysql.web-stat-filter.url-pattern=/*
datasource.druid.mysql.web-stat-filter.exclusions='*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
datasource.druid.mysql.stat-view-servlet.enabled=true
datasource.druid.mysql.stat-view-servlet.url-pattern=/druid/*
datasource.druid.mysql.stat-view-servlet.reset-enable=false