spring.profiles.active=dev,mariadb,mysqlbak,redisbak,timezone,mail,xss,bus,feign,redis

spring.cloud.bootstrap.enabled=true
spring.cloud.config.allowOverride=true
spring.cloud.config.overrideNone=true

spring.boot.admin.client.url=http://localhost:8086/admin-server
spring.boot.admin.client.instance.service-base-url=http://localhost:8081/web
spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin

spring.thymeleaf.cache=false
#spring.devtools.add-properties=false

logging.level.ROOT=INFO
logging.level.com.example.demo.feign=DEBUG
logging.level.org.springframework.amqp.rabbit=WARN
